# Generated by Django 3.0.5 on 2020-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('short_description', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.CharField(blank=True, max_length=45, null=True)),
                ('sysActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
    ]
