# Generated by Django 3.0.5 on 2020-04-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applocal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={},
        ),
    ]
