# Generated by Django 3.0.5 on 2020-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applocal', '0002_auto_20200429_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(default='a', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='complemento',
            field=models.CharField(default='a', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='rua',
            field=models.CharField(default='a', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='short_description',
            field=models.CharField(default='a', max_length=45),
            preserve_default=False,
        ),
    ]
