# Generated by Django 3.0.5 on 2020-04-29 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appculto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhup', models.DateTimeField(default=datetime.datetime(2020, 4, 29, 18, 4, 25, 207686))),
                ('qtd_pessoas', models.IntegerField(default=1)),
                ('nome', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('token', models.IntegerField(max_length=4)),
                ('sysActive', models.BooleanField(default=True)),
                ('culto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appculto.Culto')),
            ],
        ),
    ]
