# Generated by Django 3.0.5 on 2020-04-29 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='dhup',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 18, 4, 40, 321299)),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='token',
            field=models.IntegerField(),
        ),
    ]
