# Generated by Django 3.0.5 on 2020-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinscricao', '0003_auto_20200429_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='santa_ceia',
            field=models.IntegerField(default=1),
        ),
    ]
