# Generated by Django 3.0.5 on 2020-04-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applocal', '0002_auto_20200429_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=45)),
                ('limite', models.IntegerField()),
                ('sysActive', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applocal.Local')),
            ],
        ),
    ]
