# Generated by Django 3.0.5 on 2020-04-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applocal', '0003_auto_20200429_2141'),
        ('appculto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applocal.Local'),
        ),
    ]
