# Generated by Django 3.0.5 on 2020-04-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appculto', '0002_auto_20200430_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='culto',
            name='vagas',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='culto',
            name='limite',
            field=models.IntegerField(default=40),
        ),
    ]
